---
- name: Update all hosts
  hosts: all_hosts
  become: yes
  tasks:
    - name: Update apt repository cache
      apt:
        update_cache: yes
    
    - name: Upgrade all apt packages
      apt:
        upgrade: dist
